---
title: "Gov 50 Final Project"
author: "Layla Chaaraoui"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to higher education in the United States. I'd like to explore how students from inner-city or rural school districts have access to higher education versus students from private or charter districts. 

## Finding data and writing a proposal 

Potential Data Source: https://nces.ed.gov/datalab/onlinecodebook/session/codebook/ae7c2850-85e8-4c0d-a06c-d68b5513de7d 
I am worried that committing with the downloaded version will lead to problems with my project. I previously downloaded it and uploaded it into R, but I am afraid it will not be able to upload to Git. I am unsure how to cut down the data set, as I do not need many of the survey questions asked and would like to interpret specific variables, so I am linking it above for now.

Does foundation and location determine education? In this study, I plan to examine the relationship between socio-economic status and regional differences with access to higher education. I hypothesize that students who attended low-income urban and rural school districts have less access to higher education then students who attend private or charter school districts. I expect that the students within the urban and rural school districts on average have a lower socio-economic status, determined by a school's access to free lunch and other resources, have more racial diversity, and may not offer advanced educational opportunities in high school, such as counselors, Advanced Placement testing, and college advising. I expect that students who attend private or charter school districts come from higher socio-economic statuses, have less racial diversity, and have access to advanced educational opportunities in high school. The study I am evaluating is the "Educational Longitudinal Study of 2002" by the National Center of Educational Statistics. This study followed the transitions of students from high school to when they enter the work force. My sample is the students observed throughout the study from years 2002-2006, as this data is strictly about the students' high school and college involvement. There are multiple explanatory variables of interest I will be studying. In regards to the school, I would like to analyze variables like "BYURBAN" which analyzes school urbancity, "BYSCTRL" which looks at school control, "BY10FLP," which look's at the school's free-lunch categorical, and "BYA15C," which looks at if students are in college preparation programs. In regards to students, I would look at variables such as "BYRACE," which identifies a student's race or ethnicity, "BYSCHPRG," which is a student's high school program, "F1S52A" which evaluates the importance of low expenses in their post-secondary school to a student, and "F1S48H," which evaluates access to representatives for college information. The outcome variable of interest is "F2PS0__" which evaluates if a student is enrolled in a post-secondary education. It is measured by identifying whether or not a student is enrolled in post-secondary education, and if so, which type of institution the student is enrolled in. The observed pattern in the data that would support my hypothesis is if students from low-income urban and rural districts had less access to college preparation and higher institutions, which would be observed by negative responses to these variables. Students from private and Catholic suburban districts will have more access to these opportunities, observed by positive responses. A pattern that would disprove my hypothesis is if the students who lived in rural or urban low-income areas either had more access to college preparation or higher attendance rates to higher education.
